-- 2.1
SELECT * FROM SALGRADE;
-- 2.2
SELECT * FROM EMP;
-- 2.3
SELECT JOB FROM EMP;
-- 2.4
SELECT ENAME, SAL*12+NVL(COMM,0)  AS REMUNERATION FROM EMP;
-- 2.5
SELECT ENAME || ' HAS HELP THE POSITION OF PRESIDENT IN DEPT'||DEPTNO||'SINCE '||HIREDATE FROM EMP;
-- 2.6
DESC[] EMP;
-- 2.7
COLUMN SAL JUSTIFY LEFT FORMAT $ 99,990.00
COLUMN hiredate FORMAT A9;
-- 3.1
SELECT ENAME,DEPTNO,SAL FROM EMP WHERE SAL BETWEEN 1000 AND 2000;
-- 3.2
SELECT DEPTNO,ENAME FROM EMP ORDER BY DEPTNO ASC;
-- 3.3
SELECT * FROM EMP WHERE DEPTNO IN (10,20);
-- 3.4
SELECT ENAME,JOB FROM EMP WHERE JOB like 'CLERK' AND DEPTNO LIKE 20;
-- 3.5
SELECT * FROM EMP WHERE ENAME LIKE '%TH%' OR ENAME LIKE '%LL%';
-- 3.6
SELECT ENAME,JOB,NVL(SAL,0) FROM EMP ;
-- 3.7
SELECT ENAME,DEPTNO,HIREDATE FROM EMP WHERE HIREDATE LIKE '%83%';
-- 3.8
SELECT ENAME,SAL*12+NVL(COMM,0) AS ANUAL_SAL,COMM FROM EMP WHERE JOB LIKE 'SALESMAN'
ORDER BY ANUAL_SAL DESC;

