--7.1 Tạo bảng PROJECT với các column được chỉ ra dưới đây, PROJID là promary key, và
-- P_END_DATE  P_START_DATE.
-- Column name Data Type Size.
-- PROJID NUMBER 4
-- P_DESC VARCHAR2 20
-- P_START_DATE DATE
-- P_END_DATE DATE
-- BUDGET_AMOUNT NUMBER 7,2
-- MAX_NO_STAFF NUMBER 2
CREATE TABLE PROJECT(
    PROJID NUMBER(4) PRIMARY KEY,
    P_DESC VARCHAR2(20),
    P_START_DATE DATE NOT NULL,
    P_END_DATE DATE NOT NULL,
    CHECK ( P_END_DATEP_START_DATE ),
    BUDGET_AMOUNT NUMBER(7,2) NOT NULL,
    MAX_NO_STAFF NUMBER(2) NOT NULL
);
--7.2 Tạo bảng ASSIGNMENTS với các column được chỉ ra dưới đây, đồng thời cột
-- PROJID là foreign key tới bảng PROJECT, cột EMPNO là foreign key tới bảng EMP
-- Column name Data Type Size.
-- PROJID NUMBER 4 NOT NULL
-- EMPNO NUMBER 4 NOT NULL
-- A_START_DATE DATE
-- A_END_DATE DATE
-- BILL_AMOUNT NUMBER 4,2
-- ASSIGN_TYPE VARCHAR2 2
CREATE TABLE ASSIGNMENTS(
    PROJID NUMBER(4) PRIMARY KEY NOT NULL,
    EMPNO NUMBER(4) NOT NULL ,
    A_START_DATE DATE,
    A_END_DATE DATE,
    BILL_AMOUNT NUMBER(4,2),
    ASSIGN_TYPE VARCHAR2(2),
    FOREIGN KEY (PROJID) REFERENCES PROJECT(PROJID),
    FOREIGN KEY (EMPNO) REFERENCES EMP(EMPNO)
);
--7.3 Thêm column COMMENTS kiểu LONG vào bảng PROJECTS.
-- Thêm column HOURS kiểu NUMBER vào bảng ASSIGNMENTS.
ALTER TABLE PROJECTS
ADD COMMENTS LONG NOT NULL;
--7.4 Sử dụng view USER_OBJECTS hiển thị tất cả các đối tượng user sở hữu.
SELECT * FROM USER_OBJECTS;
--7.5 Thêm ràng buộc duy nhất (UNIQUE) cho 2 column PROJECT_ID và EMPNO của bảng ASSIGNMENTS.
ALTER TABLE ASSIGNMENTS ADD PROJECT_ID NUMBER(4) UNIQUE ;
ALTER TABLE ASSIGNMENTS DROP COLUMN EMPNO;
ALTER TABLE ASSIGNMENTS ADD EMPNO NUMBER(4) UNIQUE ;
--7.6 Xem các thông tin về các ràng buộc trong USER_CONSTRAINTS.
SELECT * FROM USER_CONSTRAINTS;
--7.7 Xem trong USER hiện tại có tất cả bao nhiêu bảng
SELECT COUNT(TNAME) COUNT FROM TAB;

--8.1  Thêm dữ liệu vào bảng PROJECTS.
-- PROJID 1 2
-- P_DESC WRITE C030 COURSE PROOF READ NOTES
-- P_START_DATE 02-JAN-88 01-JAN-89
-- P_END_DATE 07-JAN-88 10-JAN-89
-- BUDGET_AMOUNT 500 600
-- MAX_NO_STAFF 1 1
SELECT FROM PROJECTS;
INSERT INTO PROJECTS(PROJID,P_DESC,P_START_DATE,P_END_DATE,BUDGET_AMOUNT,MAX_NO_STAFF)
VALUES (1,'WRITE C030 COURSE','02-JAN-88','07-JAN-88',500,1 ),
        (2,'PROOF READ NOTES ','01-JAN-89','10-JAN-89',600,1 );
--8.2 Thêm dữ liệu vào bảng ASSIGNMENTS.
-- PROJID 1 1 2
-- EMPNO 7369 7902 7844
-- A_START_DATE 01-JAN-88 04-JAN-88 01-JAN-89
-- A_END_DATE 03-JAN-88 07-JAN-88 10-JAN-89
-- BILL_RATE 50.00 55.00 45.50
-- ASSIGN_TYPE WR WR PF
-- HOURS 15 20 30
SELECT * FROM ASSIGNMENTS;
INSERT INTO ASSIGNMENTS(PROJID,EMPNO,A_START_DATE,A_END_DATE,BILL_AMOUNT,ASSIGN_TYPE,HOURS)
VALUES (1,7369,'01-JAN-88','03-JAN-88',50.00,'WR',15 );
INSERT INTO ASSIGNMENTS(PROJID,EMPNO,A_START_DATE,A_END_DATE,BILL_AMOUNT,ASSIGN_TYPE,HOURS)
VALUES (2,7902,'03-JAN-88','07-JAN-88',55.00,'WR',20 );
INSERT INTO ASSIGNMENTS(PROJID,EMPNO,A_START_DATE,A_END_DATE,BILL_AMOUNT,ASSIGN_TYPE,HOURS)
VALUES (3,7844,'01-JAN-89','10-JAN-89',45.50,'PF',30 );

--8.3  Cập nhật trường ASIGNMENT_TYPE từ WT thành WR.
UPDATE ASSIGNMENTS SET ASSIGN_TYPE = 'WR' WHERE ASSIGN_TYPE='WT';

--8.4 Nhập thêm số liệu vào bảng ASSIGNMENTS.
INSERT INTO ASSIGNMENTS(PROJID,EMPNO,A_START_DATE,A_END_DATE,BILL_AMOUNT,ASSIGN_TYPE,HOURS)
VALUES (10,7369,'02-JAN-88','04-JAN-88',60.00,'WT',15 );
INSERT INTO ASSIGNMENTS(PROJID,EMPNO,A_START_DATE,A_END_DATE,BILL_AMOUNT,ASSIGN_TYPE,HOURS)
VALUES (11,7902,'03-JAN-88','05-JAN-88',75.00,'WT',20 );
INSERT INTO ASSIGNMENTS(PROJID,EMPNO,A_START_DATE,A_END_DATE,BILL_AMOUNT,ASSIGN_TYPE,HOURS)
VALUES (12,7844,'04-JAN-89','16-JAN-89',85.50,'PF',10 );

--9.1 Tạo Index trên cột PROJID cho bảng ASSIGNMENT
CREATE UNIQUE INDEX idxPro ON ASSIGNMENT(PROJID);
--9.2 Hiển thị danh sách của nhân viên thuộc sự quản lý của người có tên là 1 biến được
-- nhập từ bàn phím EMPNO ENAME JOB MGR HIREDATE SAL COMM DEPTNO
-- 7698 BLAKE MANAGER 7839 01-05-1981 2850 30
-- 7654 MARTIN SALESMAN 7698 28-09-1981 1250 1400 30
-- 7499 ALLEN SALESMAN 7698 20-02-1981 1600 300 30
-- 7844 TURNER SALESMAN 7698 08-09-1981 1500 0 30
-- 7900 JAMES CLERK 7698 03-12-1981 950 30
-- 7521 WARD SALESMAN 7698 22-02-1981 1250 500 30
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,NVL(SAL,0) AS SAL,NVL(COMM,0) AS COMM,DEPTNO
FROM EMP WHERE MGR = (SELECT EMPNO FROM EMP WHERE JOB='MANAGER' AND ENAME=&name);